repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
    - id: isort
      name: isort
      entry: isort
      require_serial: true
      language: python
      types: [python]
      args: [--multi-line=3, --line-length=88]
