repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: '5.1.4'
    hooks:
    - id: isort
      name: isort
      entry: isort
      require_serial: true
      language: python
      types: [python]
      args: [--multi-line=3, --line-length=88]
